### ISSUE TITLE
Missing images in pdf file

### ISSUE THREAD

**Issue by lebogan** [blocknotes/wkhtmltopdf-crystal#2]
I am converting a markdown document to html, then to pdf. The document has images referenced in it which show up in the html conversion. The conversion to pdf renders little icons where the images should be. Is this normal behavior for wkhtmltopdf-crystal? Can the images be rendered in the resulting pdf?
```
require "./pdfgen/*"
require "wkhtmltopdf-crystal"

html = File.read("./README.html")
pdf = Wkhtmltopdf::WkPdf.new
pdf.set_output "html_to_pdf.pdf"
pdf.convert html
```
I tried the command line wkhtmltopdf and it worked as advertised. What am I missing?

**Comment by vectorselector** [comment]
try putting a base url in the head of the html (ecr template?) document

  `<base href="<%= siteUrl %>">`

and make sure you are able to load the images from your crystal program (kemal? yourApp/public/ is the place.)
check permissions.
I use kemal and usually render the ECR first to a browser to inspect, then do the pdf.convert after the template is confirmed working

**Comment by blocknotes** [comment]
Sorry to take so long.
Yes, it could be a problem related to the path of the images.

You could try to edit the HTML and change the path of an image to the absolute local path of the image. It should work.

Also setting the base URL as suggested by @vectorselector should work.
For example, in the head of the document you put:
`<base href="file:///complete_local_path_to_root_page/">`
(the final slash is important) and then in the img tags you can use `<img src="image1.jpg">`

I have just updated one of the examples adding a base tag like this: `<base href="file://#{Dir.current}/">`
